[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.poetry]
name = "uploader-backend"
version = "0.0.1"
description = "The backend API for my cdn uploader."
authors = ["Axel <axelancerr@gmail.com>"]


[tool.poetry.dependencies]
python = "^3.10.0"
starlite = "^1.16.0"
asyncpg = "^0.26.0"
snowflake-id = "0.0.2"
pydantic = { version = "^1.10.0", extras = ["dotenv"] }


[tool.pyright]
include = ["main.py", "src"]
pythonVersion = "3.10"
typeCheckingMode = "strict"
useLibraryCodeForTypes = true

reportUnknownMemberType = false
reportMissingTypeStubs = false
